name: Terraform Export Bug
description: Raise an issue with Export-PSCFNTerraform cmdlet
title: '[TF Export:] '
assignees:
  - fireflycons
labels:
  - bug
body:
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g. Windows 10/Ubuntu 18.04 etc.
    validations:
      required: true
  - type: input
    attributes:
      label: PSCloudFormation
      description: What version of PSCloudFormation module are you using?
      placeholder: e.g. 4.1.16.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command Line
      description: What was the command line that produced the error?
      placeholder: e.g. Export-PSCFNTerraForm -StackName a-stack -WorkspaceDirectory ~/my-test-workspace
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception Details
      description: Run the above command line with -Debug switch
      placeholder: Paste full exception dump here
    validations:
      required: true
  - type: textarea
    attributes:
      label: CloudFormation
      description: |
        If possible, paste in the CloudFormation template that caused the issue.
        Even better, create a reproduction with only the affected resource(s) that cause the error.
      placeholder: Paste or drop CloudFormation
