name: Bug Report
description: Raise an issue with PSCloudFormation in general
title: '[Bug:] '
assignees:
  - fireflycons
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: Please use separate `Terraform Export Bug` template to report issues with `Export-PSCFNTerraform` by clicking **choose a different type** above.
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g. Windows 10/Ubuntu 18.04 etc.
    validations:
      required: true
  - type: input
    attributes:
      label: PowerShell
      description: What version of PowerShell are you using?
      placeholder: Enter output of $Host.Version.ToString()
    validations:
      required: true
  - type: input
    attributes:
      label: PSCloudFormation
      description: What version of PSCloudFormation module are you using?
      placeholder: e.g. 4.1.16.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command Line
      description: What was the command line that produced the error?
      placeholder: e.g. New-PSCFNStack -StackName a-stack -TemplateLocation template.yaml
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception Details
      description: Run the above command line with `-Debug` switch
      placeholder: Paste full exception dump and loaded module list here.
      render: text
    validations:
      required: true
