namespace Firefly.PSCloudFormation.Terraform.State
{
    /// <summary>
    /// Reference for an interpolated string, as will be generated by <c>!Sub</c> intrinsic
    /// </summary>
    /// <seealso cref="Firefly.PSCloudFormation.Terraform.State.Reference" />
    internal class InterpolationReference : Reference
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterpolationReference"/> class.
        /// </summary>
        /// <param name="objectAddress">The object address.</param>
        /// <param name="index">The index.</param>
        // ReSharper disable once UnusedMember.Global - User by reflection
        public InterpolationReference(string objectAddress, int index)
            : base(objectAddress, index)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InterpolationReference"/> class.
        /// </summary>
        /// <param name="objectAddress">The object address.</param>
        public InterpolationReference(string objectAddress)
            : base(objectAddress)
        {
        }

        /// <inheritdoc />
        public override string ReferenceExpression => $"\"{this.ObjectAddress}\"";
    }
}